# Generated by Django 4.2.2 on 2023-06-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='fields', to='rental.image'),
        ),
    ]
